# URL to download the Whisper base-model ZIP from Google Drive
GDRIVE_BASE_ZIP_URL = "https://drive.google.com/uc?export=download&id=1Uzz9--j8I-tACW-dGRPE5Vpl-DkMsDyg"

# URL to download your PEFT adapter ZIP from Google Drive
GDRIVE_PEFT_ZIP_URL = "https://drive.google.com/uc?export=download&id=1ciE-jeHJxev0Pk-bCdalbP1QfZPXgY_E"

# The exact filenames of the ZIPs once downloaded
BASE_ZIP_NAME  = "whisper-large-v3.zip"
PEFT_ZIP_NAME  = "final_optimized_model.zip"
