# Google Drive “export=download” URLs
GDRIVE_BASE_ZIP_URL = "https://drive.google.com/uc?export=download&id=1Uzz9--j8I-tACW-dGRPE5Vpl-DkMsDyg"
GDRIVE_PEFT_ZIP_URL = "https://drive.google.com/uc?export=download&id=1ciE-jeHJxev0Pk-bCdalbP1QfZPXgY_E"

# Local ZIP filenames (must match what you unpack)
BASE_ZIP_NAME  = "whisper-large-v3.zip"
PEFT_ZIP_NAME  = "final_optimized_model.zip"
